const VOCABULARY = [
  { id: 1, italian: "di", english: "of / from" },
  { id: 2, italian: "a", english: "to / at" },
  { id: 3, italian: "e", english: "and" },
  { id: 4, italian: "in", english: "in / into" },
  { id: 5, italian: "il", english: "the (masc. sg.)" },
  { id: 6, italian: "che", english: "that / which / who" },
  { id: 7, italian: "un", english: "a / an (masc.)" },
  { id: 8, italian: "non", english: "not / no" },
  { id: 9, italian: "la", english: "the (fem. sg.) / her" },
  { id: 10, italian: "con", english: "with" },
  { id: 11, italian: "del", english: "of the (masc. sg.)" },
  { id: 12, italian: "per", english: "for / in order to" },
  { id: 13, italian: "una", english: "a / an (fem.)" },
  { id: 14, italian: "su", english: "on / about" },
  { id: 15, italian: "si", english: "oneself / one" },
  { id: 16, italian: "mi", english: "me / myself" },
  { id: 17, italian: "ha", english: "has / he·she has" },
  { id: 18, italian: "ma", english: "but" },
  { id: 19, italian: "più", english: "more / anymore" },
  { id: 20, italian: "lo", english: "him / it (masc.)" },
  { id: 21, italian: "lei", english: "she / her / you (formal)" },
  { id: 22, italian: "lui", english: "he / him" },
  { id: 23, italian: "da", english: "from / since / by" },
  { id: 24, italian: "ci", english: "us / there / here" },
  { id: 25, italian: "se", english: "if / whether" },
  { id: 26, italian: "al", english: "to the (masc. sg.)" },
  { id: 27, italian: "quando", english: "when" },
  { id: 28, italian: "io", english: "I" },
  { id: 29, italian: "già", english: "already / of course" },
  { id: 30, italian: "sono", english: "I am / they are" },
  { id: 31, italian: "poi", english: "then / later" },
  { id: 32, italian: "o", english: "or" },
  { id: 33, italian: "anche", english: "also / too / even" },
  { id: 34, italian: "tutto", english: "everything / all" },
  { id: 35, italian: "quello", english: "that (masc.)" },
  { id: 36, italian: "dopo", english: "after / later" },
  { id: 37, italian: "qui", english: "here" },
  { id: 38, italian: "dove", english: "where" },
  { id: 39, italian: "cosa", english: "thing / what" },
  { id: 40, italian: "come", english: "how / as / like" },
  { id: 41, italian: "hai", english: "you have" },
  { id: 42, italian: "no", english: "no" },
  { id: 43, italian: "ti", english: "you / yourself (inf.)" },
  { id: 44, italian: "ho", english: "I have" },
  { id: 45, italian: "ne", english: "of it / of them" },
  { id: 46, italian: "te", english: "you (emphatic)" },
  { id: 47, italian: "gli", english: "him / the (masc. pl.)" },
  { id: 48, italian: "le", english: "her / the (fem. pl.)" },
  { id: 49, italian: "i", english: "the (masc. pl.)" },
  { id: 50, italian: "questo", english: "this (masc.)" },
  { id: 51, italian: "questa", english: "this (fem.)" },
  { id: 52, italian: "loro", english: "they / them / their" },
  { id: 53, italian: "mentre", english: "while / whereas" },
  { id: 54, italian: "perché", english: "why / because" },
  { id: 55, italian: "però", english: "however / but" },
  { id: 56, italian: "quindi", english: "so / therefore" },
  { id: 57, italian: "allora", english: "then / so / well" },
  { id: 58, italian: "ancora", english: "still / yet / again" },
  { id: 59, italian: "molto", english: "very / a lot / much" },
  { id: 60, italian: "poco", english: "little / a bit / few" },
  { id: 61, italian: "niente", english: "nothing" },
  { id: 62, italian: "qualcosa", english: "something" },
  { id: 63, italian: "qualcuno", english: "someone" },
  { id: 64, italian: "nessuno", english: "nobody / no one" },
  { id: 65, italian: "sempre", english: "always" },
  { id: 66, italian: "mai", english: "never / ever" },
  { id: 67, italian: "spesso", english: "often" },
  { id: 68, italian: "bene", english: "well / good" },
  { id: 69, italian: "male", english: "badly / bad" },
  { id: 70, italian: "adesso", english: "now" },
  { id: 71, italian: "ora", english: "now / hour" },
  { id: 72, italian: "oggi", english: "today" },
  { id: 73, italian: "ieri", english: "yesterday" },
  { id: 74, italian: "domani", english: "tomorrow" },
  { id: 75, italian: "tra", english: "between / in (time)" },
  { id: 76, italian: "verso", english: "toward / around (time)" },
  { id: 77, italian: "sotto", english: "under / below" },
  { id: 78, italian: "sopra", english: "above / on top" },
  { id: 79, italian: "dietro", english: "behind" },
  { id: 80, italian: "davanti", english: "in front of" },
  { id: 81, italian: "ogni", english: "every / each" },
  { id: 82, italian: "stesso", english: "same / himself·herself" },
  { id: 83, italian: "altro", english: "other / another" },
  { id: 84, italian: "primo", english: "first" },
  { id: 85, italian: "ultimo", english: "last" },
  { id: 86, italian: "solo", english: "only / alone" },
  { id: 87, italian: "quella", english: "that (fem.)" },
  { id: 88, italian: "così", english: "so / like this" },
  { id: 89, italian: "tanto", english: "so much / so many" },
  { id: 90, italian: "troppo", english: "too / too much" },
  { id: 91, italian: "quasi", english: "almost / nearly" },
  { id: 92, italian: "proprio", english: "exactly / truly / one's own" },
  { id: 93, italian: "davvero", english: "really / truly" },
  { id: 94, italian: "forse", english: "maybe / perhaps" },
  { id: 95, italian: "sia", english: "both / may be (subj.)" },
  { id: 96, italian: "cui", english: "whose / whom / which" },
  { id: 97, italian: "né", english: "neither / nor" },
  { id: 98, italian: "ecco", english: "here is / there is / voilà" },
  { id: 99, italian: "appena", english: "just / as soon as" },
  { id: 100, italian: "essere", english: "to be" },
  { id: 101, italian: "avere", english: "to have" },
  { id: 102, italian: "fare", english: "to do / to make" },
  { id: 103, italian: "dire", english: "to say / to tell" },
  { id: 104, italian: "andare", english: "to go" },
  { id: 105, italian: "vedere", english: "to see" },
  { id: 106, italian: "sapere", english: "to know (facts)" },
  { id: 107, italian: "potere", english: "can / to be able to" },
  { id: 108, italian: "volere", english: "to want" },
  { id: 109, italian: "dovere", english: "must / to have to" },
  { id: 110, italian: "venire", english: "to come" },
  { id: 111, italian: "stare", english: "to stay / to be (condition)" },
  { id: 112, italian: "dare", english: "to give" },
  { id: 113, italian: "pensare", english: "to think" },
  { id: 114, italian: "parlare", english: "to speak / to talk" },
  { id: 115, italian: "tornare", english: "to return / to come back" },
  { id: 116, italian: "trovare", english: "to find" },
  { id: 117, italian: "lasciare", english: "to leave / to let" },
  { id: 118, italian: "chiamare", english: "to call" },
  { id: 119, italian: "capire", english: "to understand" },
  { id: 120, italian: "credere", english: "to believe" },
  { id: 121, italian: "sentire", english: "to feel / to hear" },
  { id: 122, italian: "aspettare", english: "to wait" },
  { id: 123, italian: "chiedere", english: "to ask" },
  { id: 124, italian: "guardare", english: "to look at / to watch" },
  { id: 125, italian: "sembrare", english: "to seem / to appear" },
  { id: 126, italian: "diventare", english: "to become" },
  { id: 127, italian: "tenere", english: "to hold / to keep" },
  { id: 128, italian: "portare", english: "to bring / to carry" },
  { id: 129, italian: "mettere", english: "to put / to place" },
  { id: 130, italian: "vivere", english: "to live" },
  { id: 131, italian: "lavorare", english: "to work" },
  { id: 132, italian: "uscire", english: "to go out / to exit" },
  { id: 133, italian: "entrare", english: "to enter / to go in" },
  { id: 134, italian: "prendere", english: "to take" },
  { id: 135, italian: "ricordare", english: "to remember" },
  { id: 136, italian: "cominciare", english: "to begin / to start" },
  { id: 137, italian: "finire", english: "to finish / to end" },
  { id: 138, italian: "aprire", english: "to open" },
  { id: 139, italian: "chiudere", english: "to close" },
  { id: 140, italian: "leggere", english: "to read" },
  { id: 141, italian: "scrivere", english: "to write" },
  { id: 142, italian: "mangiare", english: "to eat" },
  { id: 143, italian: "bere", english: "to drink" },
  { id: 144, italian: "dormire", english: "to sleep" },
  { id: 145, italian: "correre", english: "to run" },
  { id: 146, italian: "camminare", english: "to walk" },
  { id: 147, italian: "ridere", english: "to laugh" },
  { id: 148, italian: "piangere", english: "to cry" },
  { id: 149, italian: "amare", english: "to love" },
  { id: 150, italian: "perdere", english: "to lose" },
  { id: 151, italian: "vincere", english: "to win / to defeat" },
  { id: 152, italian: "cadere", english: "to fall" },
  { id: 153, italian: "alzarsi", english: "to get up" },
  { id: 154, italian: "sedersi", english: "to sit down" },
  { id: 155, italian: "aiutare", english: "to help" },
  { id: 156, italian: "sperare", english: "to hope" },
  { id: 157, italian: "provare", english: "to try / to feel" },
  { id: 158, italian: "succedere", english: "to happen" },
  { id: 159, italian: "esistere", english: "to exist" },
  { id: 160, italian: "smettere", english: "to stop (doing)" },
  { id: 161, italian: "continuare", english: "to continue" },
  { id: 162, italian: "giocare", english: "to play (game)" },
  { id: 163, italian: "suonare", english: "to play (music) / to ring" },
  { id: 164, italian: "comprare", english: "to buy" },
  { id: 165, italian: "vendere", english: "to sell" },
  { id: 166, italian: "pagare", english: "to pay" },
  { id: 167, italian: "seguire", english: "to follow" },
  { id: 168, italian: "incontrare", english: "to meet" },
  { id: 169, italian: "rispondere", english: "to answer / to reply" },
  { id: 170, italian: "decidere", english: "to decide" },
  { id: 171, italian: "cambiare", english: "to change" },
  { id: 172, italian: "usare", english: "to use" },
  { id: 173, italian: "passare", english: "to pass / to spend (time)" },
  { id: 174, italian: "toccare", english: "to touch" },
  { id: 175, italian: "buttare", english: "to throw" },
  { id: 176, italian: "tirare", english: "to pull / to throw" },
  { id: 177, italian: "spingere", english: "to push" },
  { id: 178, italian: "gridare", english: "to shout / to scream" },
  { id: 179, italian: "mostrare", english: "to show" },
  { id: 180, italian: "spiegare", english: "to explain" },
  { id: 181, italian: "ricevere", english: "to receive" },
  { id: 182, italian: "mandare", english: "to send" },
  { id: 183, italian: "conoscere", english: "to know (people)" },
  { id: 184, italian: "scegliere", english: "to choose" },
  { id: 185, italian: "imparare", english: "to learn" },
  { id: 186, italian: "insegnare", english: "to teach" },
  { id: 187, italian: "costruire", english: "to build" },
  { id: 188, italian: "distruggere", english: "to destroy" },
  { id: 189, italian: "salvare", english: "to save" },
  { id: 190, italian: "uccidere", english: "to kill" },
  { id: 191, italian: "morire", english: "to die" },
  { id: 192, italian: "nascere", english: "to be born" },
  { id: 193, italian: "crescere", english: "to grow" },
  { id: 194, italian: "abbracciare", english: "to hug / to embrace" },
  { id: 195, italian: "baciare", english: "to kiss" },
  { id: 196, italian: "litigare", english: "to argue / to fight" },
  { id: 197, italian: "scappare", english: "to escape / to run away" },
  { id: 198, italian: "uomo", english: "man" },
  { id: 199, italian: "donna", english: "woman" },
  { id: 200, italian: "bambino", english: "child (masc.) / boy" },
  { id: 201, italian: "bambina", english: "child (fem.) / girl" },
  { id: 202, italian: "ragazzo", english: "boy / boyfriend / guy" },
  { id: 203, italian: "ragazza", english: "girl / girlfriend" },
  { id: 204, italian: "persona", english: "person" },
  { id: 205, italian: "gente", english: "people" },
  { id: 206, italian: "amico", english: "friend (masc.)" },
  { id: 207, italian: "amica", english: "friend (fem.)" },
  { id: 208, italian: "padre", english: "father" },
  { id: 209, italian: "madre", english: "mother" },
  { id: 210, italian: "figlio", english: "son / child (masc.)" },
  { id: 211, italian: "figlia", english: "daughter" },
  { id: 212, italian: "fratello", english: "brother" },
  { id: 213, italian: "sorella", english: "sister" },
  { id: 214, italian: "famiglia", english: "family" },
  { id: 215, italian: "marito", english: "husband" },
  { id: 216, italian: "moglie", english: "wife" },
  { id: 217, italian: "nonno", english: "grandfather" },
  { id: 218, italian: "nonna", english: "grandmother" },
  { id: 219, italian: "zio", english: "uncle" },
  { id: 220, italian: "zia", english: "aunt" },
  { id: 221, italian: "cugino", english: "cousin (masc.)" },
  { id: 222, italian: "nipote", english: "nephew / niece / grandchild" },
  { id: 223, italian: "signore", english: "mister / sir / gentleman" },
  { id: 224, italian: "signora", english: "mrs / madam / lady" },
  { id: 225, italian: "nome", english: "name" },
  { id: 226, italian: "vita", english: "life" },
  { id: 227, italian: "tempo", english: "time / weather" },
  { id: 228, italian: "anno", english: "year" },
  { id: 229, italian: "giorno", english: "day" },
  { id: 230, italian: "notte", english: "night" },
  { id: 231, italian: "mattina", english: "morning" },
  { id: 232, italian: "pomeriggio", english: "afternoon" },
  { id: 233, italian: "sera", english: "evening" },
  { id: 234, italian: "momento", english: "moment" },
  { id: 235, italian: "modo", english: "way / manner" },
  { id: 236, italian: "parte", english: "part / side" },
  { id: 237, italian: "lavoro", english: "work / job" },
  { id: 238, italian: "mondo", english: "world" },
  { id: 239, italian: "posto", english: "place / seat" },
  { id: 240, italian: "paese", english: "country / village" },
  { id: 241, italian: "città", english: "city" },
  { id: 242, italian: "strada", english: "road / street" },
  { id: 243, italian: "casa", english: "home / house" },
  { id: 244, italian: "stanza", english: "room" },
  { id: 245, italian: "porta", english: "door" },
  { id: 246, italian: "finestra", english: "window" },
  { id: 247, italian: "scala", english: "stairs / ladder" },
  { id: 248, italian: "piano", english: "floor / plan / piano" },
  { id: 249, italian: "muro", english: "wall" },
  { id: 250, italian: "tetto", english: "roof" },
  { id: 251, italian: "giardino", english: "garden" },
  { id: 252, italian: "cucina", english: "kitchen" },
  { id: 253, italian: "bagno", english: "bathroom" },
  { id: 254, italian: "camera", english: "bedroom / room" },
  { id: 255, italian: "letto", english: "bed" },
  { id: 256, italian: "tavolo", english: "table" },
  { id: 257, italian: "sedia", english: "chair" },
  { id: 258, italian: "divano", english: "sofa / couch" },
  { id: 259, italian: "specchio", english: "mirror" },
  { id: 260, italian: "lampada", english: "lamp" },
  { id: 261, italian: "acqua", english: "water" },
  { id: 262, italian: "cibo", english: "food" },
  { id: 263, italian: "pane", english: "bread" },
  { id: 264, italian: "vino", english: "wine" },
  { id: 265, italian: "caffè", english: "coffee / café" },
  { id: 266, italian: "latte", english: "milk" },
  { id: 267, italian: "carne", english: "meat" },
  { id: 268, italian: "pesce", english: "fish" },
  { id: 269, italian: "pollo", english: "chicken" },
  { id: 270, italian: "pasta", english: "pasta / dough" },
  { id: 271, italian: "riso", english: "rice" },
  { id: 272, italian: "verdura", english: "vegetables" },
  { id: 273, italian: "frutta", english: "fruit" },
  { id: 274, italian: "dolce", english: "sweet / dessert" },
  { id: 275, italian: "sale", english: "salt" },
  { id: 276, italian: "zucchero", english: "sugar" },
  { id: 277, italian: "olio", english: "oil" },
  { id: 278, italian: "burro", english: "butter" },
  { id: 279, italian: "soldi", english: "money" },
  { id: 280, italian: "prezzo", english: "price" },
  { id: 281, italian: "negozio", english: "shop / store" },
  { id: 282, italian: "mercato", english: "market" },
  { id: 283, italian: "banca", english: "bank" },
  { id: 284, italian: "ospedale", english: "hospital" },
  { id: 285, italian: "scuola", english: "school" },
  { id: 286, italian: "università", english: "university" },
  { id: 287, italian: "chiesa", english: "church" },
  { id: 288, italian: "ufficio", english: "office" },
  { id: 289, italian: "polizia", english: "police" },
  { id: 290, italian: "macchina", english: "car / machine" },
  { id: 291, italian: "treno", english: "train" },
  { id: 292, italian: "aereo", english: "airplane" },
  { id: 293, italian: "autobus", english: "bus" },
  { id: 294, italian: "barca", english: "boat" },
  { id: 295, italian: "moto", english: "motorcycle" },
  { id: 296, italian: "bicicletta", english: "bicycle" },
  { id: 297, italian: "libro", english: "book" },
  { id: 298, italian: "giornale", english: "newspaper" },
  { id: 299, italian: "parola", english: "word" },
  { id: 300, italian: "frase", english: "sentence / phrase" },
  { id: 301, italian: "voce", english: "voice" },
  { id: 302, italian: "storia", english: "story / history" },
  { id: 303, italian: "domanda", english: "question" },
  { id: 304, italian: "risposta", english: "answer" },
  { id: 305, italian: "problema", english: "problem" },
  { id: 306, italian: "idea", english: "idea" },
  { id: 307, italian: "pensiero", english: "thought" },
  { id: 308, italian: "sogno", english: "dream" },
  { id: 309, italian: "paura", english: "fear" },
  { id: 310, italian: "amore", english: "love" },
  { id: 311, italian: "odio", english: "hatred" },
  { id: 312, italian: "gioia", english: "joy" },
  { id: 313, italian: "tristezza", english: "sadness" },
  { id: 314, italian: "rabbia", english: "anger" },
  { id: 315, italian: "pace", english: "peace" },
  { id: 316, italian: "guerra", english: "war" },
  { id: 317, italian: "colpa", english: "fault / guilt" },
  { id: 318, italian: "verità", english: "truth" },
  { id: 319, italian: "bugia", english: "lie" },
  { id: 320, italian: "segreto", english: "secret" },
  { id: 321, italian: "caso", english: "case / chance" },
  { id: 322, italian: "motivo", english: "reason / motive" },
  { id: 323, italian: "senso", english: "sense / meaning" },
  { id: 324, italian: "fine", english: "end / purpose / fine" },
  { id: 325, italian: "inizio", english: "beginning" },
  { id: 326, italian: "testa", english: "head" },
  { id: 327, italian: "capelli", english: "hair" },
  { id: 328, italian: "faccia", english: "face" },
  { id: 329, italian: "occhio", english: "eye" },
  { id: 330, italian: "naso", english: "nose" },
  { id: 331, italian: "bocca", english: "mouth" },
  { id: 332, italian: "orecchio", english: "ear" },
  { id: 333, italian: "dente", english: "tooth" },
  { id: 334, italian: "collo", english: "neck" },
  { id: 335, italian: "spalla", english: "shoulder" },
  { id: 336, italian: "braccio", english: "arm" },
  { id: 337, italian: "mano", english: "hand" },
  { id: 338, italian: "dito", english: "finger" },
  { id: 339, italian: "petto", english: "chest" },
  { id: 340, italian: "pancia", english: "belly / stomach" },
  { id: 341, italian: "schiena", english: "back" },
  { id: 342, italian: "gamba", english: "leg" },
  { id: 343, italian: "ginocchio", english: "knee" },
  { id: 344, italian: "piede", english: "foot" },
  { id: 345, italian: "cuore", english: "heart" },
  { id: 346, italian: "sangue", english: "blood" },
  { id: 347, italian: "corpo", english: "body" },
  { id: 348, italian: "cielo", english: "sky" },
  { id: 349, italian: "sole", english: "sun" },
  { id: 350, italian: "luna", english: "moon" },
  { id: 351, italian: "stella", english: "star" },
  { id: 352, italian: "nuvola", english: "cloud" },
  { id: 353, italian: "pioggia", english: "rain" },
  { id: 354, italian: "neve", english: "snow" },
  { id: 355, italian: "vento", english: "wind" },
  { id: 356, italian: "fuoco", english: "fire" },
  { id: 357, italian: "terra", english: "earth / land / soil" },
  { id: 358, italian: "mare", english: "sea" },
  { id: 359, italian: "lago", english: "lake" },
  { id: 360, italian: "fiume", english: "river" },
  { id: 361, italian: "montagna", english: "mountain" },
  { id: 362, italian: "bosco", english: "forest / woods" },
  { id: 363, italian: "campo", english: "field" },
  { id: 364, italian: "fiore", english: "flower" },
  { id: 365, italian: "albero", english: "tree" },
  { id: 366, italian: "erba", english: "grass" },
  { id: 367, italian: "animale", english: "animal" },
  { id: 368, italian: "cane", english: "dog" },
  { id: 369, italian: "gatto", english: "cat" },
  { id: 370, italian: "cavallo", english: "horse" },
  { id: 371, italian: "uccello", english: "bird" },
  { id: 372, italian: "insetto", english: "insect" },
  { id: 373, italian: "vestito", english: "dress / suit / clothes" },
  { id: 374, italian: "camicia", english: "shirt" },
  { id: 375, italian: "pantaloni", english: "trousers / pants" },
  { id: 376, italian: "gonna", english: "skirt" },
  { id: 377, italian: "giacca", english: "jacket" },
  { id: 378, italian: "cappotto", english: "coat" },
  { id: 379, italian: "scarpa", english: "shoe" },
  { id: 380, italian: "borsa", english: "bag / purse" },
  { id: 381, italian: "cappello", english: "hat" },
  { id: 382, italian: "occhiali", english: "glasses" },
  { id: 383, italian: "orologio", english: "watch / clock" },
  { id: 384, italian: "anello", english: "ring" },
  { id: 385, italian: "buono", english: "good" },
  { id: 386, italian: "cattivo", english: "bad / wicked" },
  { id: 387, italian: "grande", english: "big / great" },
  { id: 388, italian: "piccolo", english: "small / little" },
  { id: 389, italian: "bello", english: "beautiful / nice" },
  { id: 390, italian: "brutto", english: "ugly / bad" },
  { id: 391, italian: "vero", english: "true / real" },
  { id: 392, italian: "falso", english: "false" },
  { id: 393, italian: "nuovo", english: "new" },
  { id: 394, italian: "vecchio", english: "old" },
  { id: 395, italian: "giovane", english: "young" },
  { id: 396, italian: "lungo", english: "long" },
  { id: 397, italian: "corto", english: "short (length)" },
  { id: 398, italian: "alto", english: "tall / high" },
  { id: 399, italian: "basso", english: "short (height) / low" },
  { id: 400, italian: "caro", english: "dear / expensive" },
  { id: 401, italian: "economico", english: "cheap / affordable" },
  { id: 402, italian: "libero", english: "free" },
  { id: 403, italian: "occupato", english: "busy / occupied" },
  { id: 404, italian: "giusto", english: "right / just / exact" },
  { id: 405, italian: "sbagliato", english: "wrong / mistaken" },
  { id: 406, italian: "facile", english: "easy" },
  { id: 407, italian: "difficile", english: "difficult" },
  { id: 408, italian: "possibile", english: "possible" },
  { id: 409, italian: "impossibile", english: "impossible" },
  { id: 410, italian: "importante", english: "important" },
  { id: 411, italian: "diverso", english: "different" },
  { id: 412, italian: "simile", english: "similar" },
  { id: 413, italian: "uguale", english: "equal / same" },
  { id: 414, italian: "forte", english: "strong" },
  { id: 415, italian: "debole", english: "weak" },
  { id: 416, italian: "veloce", english: "fast" },
  { id: 417, italian: "lento", english: "slow" },
  { id: 418, italian: "pesante", english: "heavy" },
  { id: 419, italian: "leggero", english: "light" },
  { id: 420, italian: "caldo", english: "hot / warm" },
  { id: 421, italian: "freddo", english: "cold" },
  { id: 422, italian: "fresco", english: "fresh / cool" },
  { id: 423, italian: "pieno", english: "full" },
  { id: 424, italian: "vuoto", english: "empty" },
  { id: 425, italian: "aperto", english: "open" },
  { id: 426, italian: "chiuso", english: "closed" },
  { id: 427, italian: "pulito", english: "clean" },
  { id: 428, italian: "sporco", english: "dirty" },
  { id: 429, italian: "silenzioso", english: "quiet / silent" },
  { id: 430, italian: "rumoroso", english: "noisy / loud" },
  { id: 431, italian: "stanco", english: "tired" },
  { id: 432, italian: "sveglio", english: "awake / alert" },
  { id: 433, italian: "pronto", english: "ready" },
  { id: 434, italian: "sicuro", english: "safe / sure / certain" },
  { id: 435, italian: "pericoloso", english: "dangerous" },
  { id: 436, italian: "felice", english: "happy" },
  { id: 437, italian: "triste", english: "sad" },
  { id: 438, italian: "arrabbiato", english: "angry" },
  { id: 439, italian: "preoccupato", english: "worried" },
  { id: 440, italian: "sorpreso", english: "surprised" },
  { id: 441, italian: "contento", english: "happy / content" },
  { id: 442, italian: "deluso", english: "disappointed" },
  { id: 443, italian: "nervoso", english: "nervous" },
  { id: 444, italian: "tranquillo", english: "calm / quiet" },
  { id: 445, italian: "strano", english: "strange / weird" },
  { id: 446, italian: "normale", english: "normal" },
  { id: 447, italian: "famoso", english: "famous" },
  { id: 448, italian: "necessario", english: "necessary" },
  { id: 449, italian: "speciale", english: "special" },
  { id: 450, italian: "semplice", english: "simple" },
  { id: 451, italian: "complicato", english: "complicated" },
  { id: 452, italian: "interessante", english: "interesting" },
  { id: 453, italian: "noioso", english: "boring" },
  { id: 454, italian: "divertente", english: "fun / entertaining" },
  { id: 455, italian: "bravo", english: "good / well done" },
  { id: 456, italian: "povero", english: "poor" },
  { id: 457, italian: "ricco", english: "rich" },
  { id: 458, italian: "gentile", english: "kind / polite" },
  { id: 459, italian: "educato", english: "polite / well-mannered" },
  { id: 460, italian: "onesto", english: "honest" },
  { id: 461, italian: "coraggioso", english: "brave" },
  { id: 462, italian: "pigro", english: "lazy" },
  { id: 463, italian: "intelligente", english: "intelligent" },
  { id: 464, italian: "stupido", english: "stupid" },
  { id: 465, italian: "furbo", english: "clever / cunning" },
  { id: 466, italian: "paziente", english: "patient" },
  { id: 467, italian: "impaziante", english: "impatient" },
  { id: 468, italian: "grasso", english: "fat" },
  { id: 469, italian: "magro", english: "thin" },
  { id: 470, italian: "sano", english: "healthy" },
  { id: 471, italian: "malato", english: "ill / sick" },
  { id: 472, italian: "morto", english: "dead" },
  { id: 473, italian: "vivo", english: "alive" },
  { id: 474, italian: "intero", english: "whole / entire" },
  { id: 475, italian: "metà", english: "half" },
  { id: 476, italian: "numero", english: "number" },
  { id: 477, italian: "tipo", english: "type / kind" },
  { id: 478, italian: "forma", english: "form / shape" },
  { id: 479, italian: "colore", english: "color" },
  { id: 480, italian: "rosso", english: "red" },
  { id: 481, italian: "blu", english: "blue" },
  { id: 482, italian: "verde", english: "green" },
  { id: 483, italian: "giallo", english: "yellow" },
  { id: 484, italian: "bianco", english: "white" },
  { id: 485, italian: "nero", english: "black" },
  { id: 486, italian: "grigio", english: "gray" },
  { id: 487, italian: "arancione", english: "orange" },
  { id: 488, italian: "viola", english: "purple" },
  { id: 489, italian: "rosa", english: "pink" },
  { id: 490, italian: "marrone", english: "brown" },
  { id: 491, italian: "chiaro", english: "light / clear" },
  { id: 492, italian: "scuro", english: "dark" },
  { id: 493, italian: "duro", english: "hard" },
  { id: 494, italian: "morbido", english: "soft" },
  { id: 495, italian: "liscio", english: "smooth" },
  { id: 496, italian: "ruvido", english: "rough" },
  { id: 497, italian: "lucido", english: "shiny" },
  { id: 498, italian: "opaco", english: "dull / opaque" },
  { id: 499, italian: "profondo", english: "deep" },
  { id: 500, italian: "superficiale", english: "shallow / superficial" },
  { id: 501, italian: "largo", english: "wide / broad" },
  { id: 502, italian: "stretto", english: "narrow / tight" },
  { id: 503, italian: "dritto", english: "straight" },
  { id: 504, italian: "curvo", english: "curved" },
  { id: 505, italian: "rotondo", english: "round" },
  { id: 506, italian: "quadrato", english: "square" },
  { id: 507, italian: "triangolare", english: "triangular" },
  { id: 508, italian: "certo", english: "certain / sure" },
  { id: 509, italian: "preciso", english: "precise / exact" },
  { id: 510, italian: "vago", english: "vague" },
  { id: 511, italian: "confuso", english: "confused / confusing" },
  { id: 512, italian: "immediato", english: "immediate" },
  { id: 513, italian: "continuo", english: "continuous" },
  { id: 514, italian: "regolare", english: "regular" },
  { id: 515, italian: "irregolare", english: "irregular" },
  { id: 516, italian: "uno", english: "one" },
  { id: 517, italian: "due", english: "two" },
  { id: 518, italian: "tre", english: "three" },
  { id: 519, italian: "quattro", english: "four" },
  { id: 520, italian: "cinque", english: "five" },
  { id: 521, italian: "sei", english: "six" },
  { id: 522, italian: "sette", english: "seven" },
  { id: 523, italian: "otto", english: "eight" },
  { id: 524, italian: "nove", english: "nine" },
  { id: 525, italian: "dieci", english: "ten" },
  { id: 526, italian: "undici", english: "eleven" },
  { id: 527, italian: "dodici", english: "twelve" },
  { id: 528, italian: "venti", english: "twenty" },
  { id: 529, italian: "trenta", english: "thirty" },
  { id: 530, italian: "quaranta", english: "forty" },
  { id: 531, italian: "cinquanta", english: "fifty" },
  { id: 532, italian: "cento", english: "hundred" },
  { id: 533, italian: "mille", english: "thousand" },
  { id: 534, italian: "secondo", english: "second" },
  { id: 535, italian: "minuto", english: "minute" },
  { id: 536, italian: "quarto", english: "quarter / fourth" },
  { id: 537, italian: "settimana", english: "week" },
  { id: 538, italian: "mese", english: "month" },
  { id: 539, italian: "stagione", english: "season" },
  { id: 540, italian: "primavera", english: "spring" },
  { id: 541, italian: "estate", english: "summer" },
  { id: 542, italian: "autunno", english: "autumn" },
  { id: 543, italian: "inverno", english: "winter" },
  { id: 544, italian: "lunedì", english: "Monday" },
  { id: 545, italian: "martedì", english: "Tuesday" },
  { id: 546, italian: "mercoledì", english: "Wednesday" },
  { id: 547, italian: "giovedì", english: "Thursday" },
  { id: 548, italian: "venerdì", english: "Friday" },
  { id: 549, italian: "sabato", english: "Saturday" },
  { id: 550, italian: "domenica", english: "Sunday" },
  { id: 551, italian: "gennaio", english: "January" },
  { id: 552, italian: "febbraio", english: "February" },
  { id: 553, italian: "marzo", english: "March" },
  { id: 554, italian: "aprile", english: "April" },
  { id: 555, italian: "maggio", english: "May" },
  { id: 556, italian: "giugno", english: "June" },
  { id: 557, italian: "luglio", english: "July" },
  { id: 558, italian: "agosto", english: "August" },
  { id: 559, italian: "settembre", english: "September" },
  { id: 560, italian: "ottobre", english: "October" },
  { id: 561, italian: "novembre", english: "November" },
  { id: 562, italian: "dicembre", english: "December" },
  { id: 563, italian: "mattino", english: "morning" },
  { id: 564, italian: "mezzanotte", english: "midnight" },
  { id: 565, italian: "mezzogiorno", english: "noon" },
  { id: 566, italian: "tardi", english: "late" },
  { id: 567, italian: "presto", english: "early / soon" },
  { id: 568, italian: "subito", english: "right away / immediately" },
  { id: 569, italian: "lì", english: "there" },
  { id: 570, italian: "là", english: "there (further)" },
  { id: 571, italian: "giù", english: "down" },
  { id: 572, italian: "fuori", english: "outside / out" },
  { id: 573, italian: "dentro", english: "inside" },
  { id: 574, italian: "vicino", english: "near / close" },
  { id: 575, italian: "lontano", english: "far" },
  { id: 576, italian: "insieme", english: "together" },
  { id: 577, italian: "circa", english: "about / approximately" },
  { id: 578, italian: "soltanto", english: "only / just" },
  { id: 579, italian: "almeno", english: "at least" },
  { id: 580, italian: "soprattutto", english: "especially / above all" },
  { id: 581, italian: "comunque", english: "anyway / however" },
  { id: 582, italian: "amicizia", english: "friendship" },
  { id: 583, italian: "relazione", english: "relationship" },
  { id: 584, italian: "incontro", english: "meeting / encounter" },
  { id: 585, italian: "appuntamento", english: "appointment / date" },
  { id: 586, italian: "festa", english: "party / holiday / celebration" },
  { id: 587, italian: "compleanno", english: "birthday" },
  { id: 588, italian: "regalo", english: "gift / present" },
  { id: 589, italian: "viaggio", english: "trip / journey" },
  { id: 590, italian: "vacanza", english: "vacation / holiday" },
  { id: 591, italian: "turista", english: "tourist" },
  { id: 592, italian: "albergo", english: "hotel" },
  { id: 593, italian: "ristorante", english: "restaurant" },
  { id: 594, italian: "bar", english: "bar / café" },
  { id: 595, italian: "menu", english: "menu" },
  { id: 596, italian: "conto", english: "bill / account / count" },
  { id: 597, italian: "cameriere", english: "waiter" },
  { id: 598, italian: "ricetta", english: "recipe" },
  { id: 599, italian: "piatto", english: "dish / plate" },
  { id: 600, italian: "bicchiere", english: "glass" },
  { id: 601, italian: "bottiglia", english: "bottle" },
  { id: 602, italian: "forchetta", english: "fork" },
  { id: 603, italian: "coltello", english: "knife" },
  { id: 604, italian: "cucchiaio", english: "spoon" },
  { id: 605, italian: "tovagliolo", english: "napkin" },
  { id: 606, italian: "colazione", english: "breakfast" },
  { id: 607, italian: "pranzo", english: "lunch" },
  { id: 608, italian: "cena", english: "dinner" },
  { id: 609, italian: "spuntino", english: "snack" },
  { id: 610, italian: "medico", english: "doctor" },
  { id: 611, italian: "infermiere", english: "nurse" },
  { id: 612, italian: "avvocato", english: "lawyer" },
  { id: 613, italian: "ingegnere", english: "engineer" },
  { id: 614, italian: "architetto", english: "architect" },
  { id: 615, italian: "insegnante", english: "teacher" },
  { id: 616, italian: "studente", english: "student" },
  { id: 617, italian: "professore", english: "professor" },
  { id: 618, italian: "direttore", english: "director / manager" },
  { id: 619, italian: "capo", english: "boss / head" },
  { id: 620, italian: "collega", english: "colleague" },
  { id: 621, italian: "impiegato", english: "employee / clerk" },
  { id: 622, italian: "imprenditore", english: "entrepreneur" },
  { id: 623, italian: "artista", english: "artist" },
  { id: 624, italian: "scrittore", english: "writer" },
  { id: 625, italian: "attore", english: "actor" },
  { id: 626, italian: "cantante", english: "singer" },
  { id: 627, italian: "musicista", english: "musician" },
  { id: 628, italian: "giornalista", english: "journalist" },
  { id: 629, italian: "politico", english: "politician" },
  { id: 630, italian: "poliziotto", english: "policeman" },
  { id: 631, italian: "soldato", english: "soldier" },
  { id: 632, italian: "cuoco", english: "cook / chef" },
  { id: 633, italian: "operaio", english: "worker / laborer" },
  { id: 634, italian: "contadino", english: "farmer" },
  { id: 635, italian: "commerciante", english: "shopkeeper / merchant" },
  { id: 636, italian: "proprietario", english: "owner" },
  { id: 637, italian: "cliente", english: "customer / client" },
  { id: 638, italian: "passante", english: "passerby" },
  { id: 639, italian: "straniero", english: "foreigner" },
  { id: 640, italian: "lingua", english: "language / tongue" },
  { id: 641, italian: "cultura", english: "culture" },
  { id: 642, italian: "tradizione", english: "tradition" },
  { id: 643, italian: "musica", english: "music" },
  { id: 644, italian: "canzone", english: "song" },
  { id: 645, italian: "film", english: "film / movie" },
  { id: 646, italian: "teatro", english: "theater" },
  { id: 647, italian: "arte", english: "art" },
  { id: 648, italian: "pittura", english: "painting" },
  { id: 649, italian: "scultura", english: "sculpture" },
  { id: 650, italian: "fotografia", english: "photography / photograph" },
  { id: 651, italian: "sport", english: "sport" },
  { id: 652, italian: "calcio", english: "football / soccer / kick" },
  { id: 653, italian: "pallacanestro", english: "basketball" },
  { id: 654, italian: "nuoto", english: "swimming" },
  { id: 655, italian: "corsa", english: "running / race" },
  { id: 656, italian: "gara", english: "competition / race" },
  { id: 657, italian: "squadra", english: "team" },
  { id: 658, italian: "giocatore", english: "player" },
  { id: 659, italian: "allenatore", english: "coach / trainer" },
  { id: 660, italian: "stadio", english: "stadium" },
  { id: 661, italian: "piscina", english: "swimming pool" },
  { id: 662, italian: "palestra", english: "gym" },
  { id: 663, italian: "telefono", english: "telephone / phone" },
  { id: 664, italian: "cellulare", english: "mobile phone / cell phone" },
  { id: 665, italian: "computer", english: "computer" },
  { id: 666, italian: "internet", english: "internet" },
  { id: 667, italian: "email", english: "email" },
  { id: 668, italian: "sito", english: "website / site" },
  { id: 669, italian: "app", english: "app" },
  { id: 670, italian: "schermo", english: "screen" },
  { id: 671, italian: "tastiera", english: "keyboard" },
  { id: 672, italian: "mouse", english: "mouse" },
  { id: 673, italian: "programma", english: "program" },
  { id: 674, italian: "notizia", english: "news / piece of news" },
  { id: 675, italian: "messaggio", english: "message" },
  { id: 676, italian: "foto", english: "photo" },
  { id: 677, italian: "video", english: "video" },
  { id: 678, italian: "suono", english: "sound" },
  { id: 679, italian: "luce", english: "light" },
  { id: 680, italian: "ombra", english: "shadow / shade" },
  { id: 681, italian: "dimensione", english: "size / dimension" },
  { id: 682, italian: "peso", english: "weight" },
  { id: 683, italian: "altezza", english: "height" },
  { id: 684, italian: "larghezza", english: "width" },
  { id: 685, italian: "lunghezza", english: "length" },
  { id: 686, italian: "temperatura", english: "temperature" },
  { id: 687, italian: "velocità", english: "speed" },
  { id: 688, italian: "forza", english: "strength / force" },
  { id: 689, italian: "energia", english: "energy" },
  { id: 690, italian: "materiale", english: "material" },
  { id: 691, italian: "legno", english: "wood" },
  { id: 692, italian: "ferro", english: "iron" },
  { id: 693, italian: "pietra", english: "stone" },
  { id: 694, italian: "vetro", english: "glass" },
  { id: 695, italian: "plastica", english: "plastic" },
  { id: 696, italian: "carta", english: "paper" },
  { id: 697, italian: "tessuto", english: "fabric / tissue" },
  { id: 698, italian: "pelle", english: "skin / leather" },
  { id: 699, italian: "oro", english: "gold" },
  { id: 700, italian: "argento", english: "silver" },
  { id: 701, italian: "governo", english: "government" },
  { id: 702, italian: "stato", english: "state / status / has been" },
  { id: 703, italian: "legge", english: "law" },
  { id: 704, italian: "diritto", english: "right / law" },
  { id: 705, italian: "politica", english: "politics / policy" },
  { id: 706, italian: "elezione", english: "election" },
  { id: 707, italian: "partito", english: "party (political)" },
  { id: 708, italian: "presidente", english: "president" },
  { id: 709, italian: "ministro", english: "minister" },
  { id: 710, italian: "parlamento", english: "parliament" },
  { id: 711, italian: "economia", english: "economy" },
  { id: 712, italian: "impresa", english: "company / enterprise" },
  { id: 713, italian: "azienda", english: "company / firm" },
  { id: 714, italian: "prodotto", english: "product" },
  { id: 715, italian: "servizio", english: "service" },
  { id: 716, italian: "qualità", english: "quality" },
  { id: 717, italian: "risultato", english: "result" },
  { id: 718, italian: "effetto", english: "effect" },
  { id: 719, italian: "causa", english: "cause" },
  { id: 720, italian: "conseguenza", english: "consequence" },
  { id: 721, italian: "soluzione", english: "solution" },
  { id: 722, italian: "metodo", english: "method" },
  { id: 723, italian: "sistema", english: "system" },
  { id: 724, italian: "processo", english: "process" },
  { id: 725, italian: "progetto", english: "project / plan" },
  { id: 726, italian: "obiettivo", english: "objective / goal" },
  { id: 727, italian: "accordo", english: "agreement" },
  { id: 728, italian: "contratto", english: "contract" },
  { id: 729, italian: "documento", english: "document" },
  { id: 730, italian: "rapporto", english: "report / relationship" },
  { id: 731, italian: "analisi", english: "analysis" },
  { id: 732, italian: "ricerca", english: "research / search" },
  { id: 733, italian: "scoperta", english: "discovery" },
  { id: 734, italian: "invenzione", english: "invention" },
  { id: 735, italian: "tecnologia", english: "technology" },
  { id: 736, italian: "scienza", english: "science" },
  { id: 737, italian: "esperimento", english: "experiment" },
  { id: 738, italian: "teoria", english: "theory" },
  { id: 739, italian: "prova", english: "proof / test" },
  { id: 740, italian: "errore", english: "error / mistake" },
  { id: 741, italian: "successo", english: "success" },
  { id: 742, italian: "fallimento", english: "failure" },
  { id: 743, italian: "rischio", english: "risk" },
  { id: 744, italian: "opportunità", english: "opportunity" },
  { id: 745, italian: "vantaggio", english: "advantage" },
  { id: 746, italian: "svantaggio", english: "disadvantage" },
  { id: 747, italian: "situazione", english: "situation" },
  { id: 748, italian: "condizione", english: "condition" },
  { id: 749, italian: "circostanza", english: "circumstance" },
  { id: 750, italian: "ambiente", english: "environment" },
  { id: 751, italian: "natura", english: "nature" },
  { id: 752, italian: "clima", english: "climate" },
  { id: 753, italian: "risorse", english: "resources" },
  { id: 754, italian: "sviluppo", english: "development" },
  { id: 755, italian: "crescita", english: "growth" },
  { id: 756, italian: "cambiamento", english: "change" },
  { id: 757, italian: "movimento", english: "movement" },
  { id: 758, italian: "direzione", english: "direction" },
  { id: 759, italian: "distanza", english: "distance" },
  { id: 760, italian: "confine", english: "border / limit" },
  { id: 761, italian: "centro", english: "center" },
  { id: 762, italian: "margine", english: "margin / edge" },
  { id: 763, italian: "spazio", english: "space" },
  { id: 764, italian: "durata", english: "duration" },
  { id: 765, italian: "frequenza", english: "frequency" },
  { id: 766, italian: "quantità", english: "quantity / amount" },
  { id: 767, italian: "gruppo", english: "group" },
  { id: 768, italian: "classe", english: "class / classroom" },
  { id: 769, italian: "lezione", english: "lesson" },
  { id: 770, italian: "corso", english: "course" },
  { id: 771, italian: "esame", english: "exam" },
  { id: 772, italian: "voto", english: "grade / vote" },
  { id: 773, italian: "diploma", english: "diploma" },
  { id: 774, italian: "laurea", english: "degree / graduation" },
  { id: 775, italian: "compito", english: "homework / task" },
  { id: 776, italian: "esercizio", english: "exercise" },
  { id: 777, italian: "materia", english: "subject (school)" },
  { id: 778, italian: "matematica", english: "mathematics" },
  { id: 779, italian: "scienze", english: "science" },
  { id: 780, italian: "italiano", english: "Italian" },
  { id: 781, italian: "inglese", english: "English" },
  { id: 782, italian: "francese", english: "French" },
  { id: 783, italian: "spagnolo", english: "Spanish" },
  { id: 784, italian: "tedesco", english: "German" },
  { id: 785, italian: "russo", english: "Russian" },
  { id: 786, italian: "cinese", english: "Chinese" },
  { id: 787, italian: "giapponese", english: "Japanese" },
  { id: 788, italian: "americano", english: "American" },
  { id: 789, italian: "europeo", english: "European" },
  { id: 790, italian: "nazione", english: "nation" },
  { id: 791, italian: "continente", english: "continent" },
  { id: 792, italian: "isola", english: "island" },
  { id: 793, italian: "penisola", english: "peninsula" },
  { id: 794, italian: "regione", english: "region" },
  { id: 795, italian: "provincia", english: "province" },
  { id: 796, italian: "comune", english: "municipality / common" },
  { id: 797, italian: "quartiere", english: "neighborhood" },
  { id: 798, italian: "piazza", english: "square / plaza" },
  { id: 799, italian: "via", english: "street / way" },
  { id: 800, italian: "viale", english: "avenue / boulevard" },
  { id: 801, italian: "vicolo", english: "alley" },
  { id: 802, italian: "incrocio", english: "intersection / crossroads" },
  { id: 803, italian: "semaforo", english: "traffic light" },
  { id: 804, italian: "ponte", english: "bridge" },
  { id: 805, italian: "tunnel", english: "tunnel" },
  { id: 806, italian: "galleria", english: "gallery / tunnel" },
  { id: 807, italian: "stazione", english: "station" },
  { id: 808, italian: "aeroporto", english: "airport" },
  { id: 809, italian: "porto", english: "port / harbor" },
  { id: 810, italian: "fermata", english: "stop (bus/tram)" },
  { id: 811, italian: "biglietto", english: "ticket" },
  { id: 812, italian: "passaporto", english: "passport" },
  { id: 813, italian: "valigia", english: "suitcase" },
  { id: 814, italian: "zaino", english: "backpack" },
  { id: 815, italian: "salute", english: "health" },
  { id: 816, italian: "malattia", english: "illness / disease" },
  { id: 817, italian: "dolore", english: "pain" },
  { id: 818, italian: "febbre", english: "fever" },
  { id: 819, italian: "tosse", english: "cough" },
  { id: 820, italian: "raffreddore", english: "cold (illness)" },
  { id: 821, italian: "influenza", english: "flu" },
  { id: 822, italian: "operazione", english: "operation" },
  { id: 823, italian: "cura", english: "treatment / care" },
  { id: 824, italian: "medicina", english: "medicine" },
  { id: 825, italian: "farmacia", english: "pharmacy" },
  { id: 826, italian: "pillola", english: "pill" },
  { id: 827, italian: "dottore", english: "doctor" },
  { id: 828, italian: "emergenza", english: "emergency" },
  { id: 829, italian: "ambulanza", english: "ambulance" },
  { id: 830, italian: "pompiere", english: "firefighter" },
  { id: 831, italian: "vigile", english: "traffic warden / police officer" },
  { id: 832, italian: "coraggio", english: "courage" },
  { id: 833, italian: "speranza", english: "hope" },
  { id: 834, italian: "fiducia", english: "trust / confidence" },
  { id: 835, italian: "rispetto", english: "respect" },
  { id: 836, italian: "orgoglio", english: "pride" },
  { id: 837, italian: "vergogna", english: "shame" },
  { id: 838, italian: "perdono", english: "forgiveness" },
  { id: 839, italian: "scusa", english: "excuse / apology" },
  { id: 840, italian: "grazie", english: "thank you" },
  { id: 841, italian: "prego", english: "you're welcome / please" },
  { id: 842, italian: "ciao", english: "hello / goodbye (informal)" },
  { id: 843, italian: "arrivederci", english: "goodbye" },
  { id: 844, italian: "salve", english: "hello (formal)" },
  { id: 845, italian: "buongiorno", english: "good morning" },
  { id: 846, italian: "buonasera", english: "good evening" },
  { id: 847, italian: "buonanotte", english: "good night" },
  { id: 848, italian: "benvenuto", english: "welcome" },
  { id: 849, italian: "basta", english: "enough / stop" },
  { id: 850, italian: "aiuto", english: "help!" },
  { id: 851, italian: "attenzione", english: "attention / caution" },
  { id: 852, italian: "pericolo", english: "danger" },
  { id: 853, italian: "vietato", english: "forbidden / prohibited" },
  { id: 854, italian: "permesso", english: "permission / excuse me" },
  { id: 855, italian: "disponibile", english: "available" },
  { id: 856, italian: "raramente", english: "rarely" },
  { id: 857, italian: "normalmente", english: "normally" },
  { id: 858, italian: "generalmente", english: "generally" },
  { id: 859, italian: "probabilmente", english: "probably" },
  { id: 860, italian: "fortunatamente", english: "fortunately" },
  { id: 861, italian: "purtroppo", english: "unfortunately" },
  { id: 862, italian: "ovviamente", english: "obviously" },
  { id: 863, italian: "chiaramente", english: "clearly" },
  { id: 864, italian: "certamente", english: "certainly" },
  { id: 865, italian: "assolutamente", english: "absolutely" },
  { id: 866, italian: "esattamente", english: "exactly" },
  { id: 867, italian: "veramente", english: "really / truly" },
  { id: 868, italian: "praticamente", english: "practically" },
  { id: 869, italian: "tipicamente", english: "typically" },
  { id: 870, italian: "principalmente", english: "mainly / primarily" },
  { id: 871, italian: "direttamente", english: "directly" },
  { id: 872, italian: "immediatamente", english: "immediately" },
  { id: 873, italian: "automaticamente", english: "automatically" },
  { id: 874, italian: "naturalmente", english: "naturally / of course" },
  { id: 875, italian: "particolarmente", english: "particularly" },
  { id: 876, italian: "specialmente", english: "especially" },
  { id: 877, italian: "solamente", english: "only" },
  { id: 878, italian: "semplicemente", english: "simply" },
  { id: 879, italian: "recentemente", english: "recently" },
  { id: 880, italian: "attualmente", english: "currently" },
  { id: 881, italian: "finalmente", english: "finally" },
  { id: 882, italian: "improvvisamente", english: "suddenly" },
  { id: 883, italian: "rapidamente", english: "quickly" },
  { id: 884, italian: "lentamente", english: "slowly" },
  { id: 885, italian: "facilmente", english: "easily" },
  { id: 886, italian: "difficilmente", english: "with difficulty" },
  { id: 887, italian: "sicuramente", english: "surely / certainly" },
  { id: 888, italian: "ovunque", english: "everywhere" },
  { id: 889, italian: "altrove", english: "elsewhere" },
  { id: 890, italian: "dappertutto", english: "everywhere" },
  { id: 891, italian: "tuttavia", english: "nevertheless" },
  { id: 892, italian: "invece", english: "instead / on the other hand" },
  { id: 893, italian: "oppure", english: "or else / or" },
  { id: 894, italian: "altrimenti", english: "otherwise" },
  { id: 895, italian: "eppure", english: "yet / and yet" },
  { id: 896, italian: "inoltre", english: "furthermore / moreover" },
  { id: 897, italian: "infine", english: "finally / in the end" },
  { id: 898, italian: "dunque", english: "therefore / well" },
  { id: 899, italian: "pertanto", english: "therefore / consequently" },
  { id: 900, italian: "poiché", english: "since / because" },
  { id: 901, italian: "affinché", english: "so that / in order that" },
  { id: 902, italian: "sebbene", english: "although / even though" },
  { id: 903, italian: "nonostante", english: "despite / notwithstanding" },
  { id: 904, italian: "malgrado", english: "despite / in spite of" },
  { id: 905, italian: "grado", english: "degree / grade" },
  { id: 906, italian: "livello", english: "level" },
  { id: 907, italian: "categoria", english: "category" },
  { id: 908, italian: "genere", english: "type / gender / genre" },
  { id: 909, italian: "specie", english: "species / kind" },
  { id: 910, italian: "varietà", english: "variety" },
  { id: 911, italian: "versione", english: "version" },
  { id: 912, italian: "modello", english: "model" },
  { id: 913, italian: "esempio", english: "example" },
  { id: 914, italian: "fatto", english: "fact" },
  { id: 915, italian: "dato", english: "data point / given" },
  { id: 916, italian: "fonte", english: "source" },
  { id: 917, italian: "origine", english: "origin" },
  { id: 918, italian: "base", english: "base / basis" },
  { id: 919, italian: "struttura", english: "structure" },
  { id: 920, italian: "funzione", english: "function" },
  { id: 921, italian: "ruolo", english: "role" },
  { id: 922, italian: "scopo", english: "purpose / aim" },
  { id: 923, italian: "missione", english: "mission" },
  { id: 924, italian: "incarico", english: "assignment / mission" },
  { id: 925, italian: "azione", english: "action" },
  { id: 926, italian: "reazione", english: "reaction" },
  { id: 927, italian: "scelta", english: "choice" },
  { id: 928, italian: "decisione", english: "decision" },
  { id: 929, italian: "proposta", english: "proposal" },
  { id: 930, italian: "offerta", english: "offer" },
  { id: 931, italian: "richiesta", english: "request" },
  { id: 932, italian: "bisogno", english: "need" },
  { id: 933, italian: "desiderio", english: "desire / wish" },
  { id: 934, italian: "intenzione", english: "intention" },
  { id: 935, italian: "sforzo", english: "effort" },
  { id: 936, italian: "tentativo", english: "attempt" },
  { id: 937, italian: "progresso", english: "progress" },
  { id: 938, italian: "miglioramento", english: "improvement" },
  { id: 939, italian: "peggioramento", english: "worsening" },
  { id: 940, italian: "differenza", english: "difference" },
  { id: 941, italian: "somiglianza", english: "similarity" },
  { id: 942, italian: "contrasto", english: "contrast" },
  { id: 943, italian: "conflitto", english: "conflict" },
  { id: 944, italian: "equilibrio", english: "balance" },
  { id: 945, italian: "armonia", english: "harmony" },
];