// ── CATEGORIES ────────────────────────────────────────────────────────────────
const CATEGORIES = [
  { id: "greetings",    name: "Greetings & Phrases",  emoji: "👋" },
  { id: "restaurant",   name: "At the Restaurant",     emoji: "🍽️" },
  { id: "bar",          name: "Bar & Café",             emoji: "☕" },
  { id: "shopping",     name: "Shopping",               emoji: "🛍️" },
  { id: "transport",    name: "Getting Around",         emoji: "🚌" },
  { id: "numbers",      name: "Numbers & Time",         emoji: "🔢" },
  { id: "family",       name: "Family & People",        emoji: "👪" },
  { id: "hotel",        name: "Accommodation",          emoji: "🏨" },
  { id: "verbs",        name: "Useful Verbs",           emoji: "⚡" },
  { id: "adjectives",   name: "Describing Things",      emoji: "✨" },
  { id: "emergencies",  name: "Emergencies",            emoji: "🆘" },
  { id: "weather",      name: "Weather & Nature",       emoji: "🌤️" },
];

// ── VOCABULARY ────────────────────────────────────────────────────────────────
// { id, italian, english, category }
const VOCABULARY = [

  // ── Greetings & Phrases (25) ──────────────────────────────────────────────
  { id:   1, italian: "ciao",                   english: "hello / goodbye (informal)",       category: "greetings" },
  { id:   2, italian: "salve",                  english: "hello (neutral)",                   category: "greetings" },
  { id:   3, italian: "buongiorno",             english: "good morning",                      category: "greetings" },
  { id:   4, italian: "buonasera",              english: "good evening",                      category: "greetings" },
  { id:   5, italian: "buonanotte",             english: "good night",                        category: "greetings" },
  { id:   6, italian: "arrivederci",            english: "goodbye (formal)",                  category: "greetings" },
  { id:   7, italian: "a presto",               english: "see you soon",                      category: "greetings" },
  { id:   8, italian: "per favore",             english: "please",                            category: "greetings" },
  { id:   9, italian: "grazie",                 english: "thank you",                         category: "greetings" },
  { id:  10, italian: "prego",                  english: "you're welcome",                    category: "greetings" },
  { id:  11, italian: "scusi",                  english: "excuse me (formal)",                category: "greetings" },
  { id:  12, italian: "mi dispiace",            english: "I'm sorry",                         category: "greetings" },
  { id:  13, italian: "non capisco",            english: "I don't understand",                category: "greetings" },
  { id:  14, italian: "non parlo italiano",     english: "I don't speak Italian",             category: "greetings" },
  { id:  15, italian: "parla inglese?",         english: "do you speak English?",             category: "greetings" },
  { id:  16, italian: "mi chiamo...",           english: "my name is...",                     category: "greetings" },
  { id:  17, italian: "come stai?",             english: "how are you? (informal)",           category: "greetings" },
  { id:  18, italian: "come sta?",              english: "how are you? (formal)",             category: "greetings" },
  { id:  19, italian: "bene, grazie",           english: "well, thank you",                   category: "greetings" },
  { id:  20, italian: "così così",              english: "so-so",                             category: "greetings" },
  { id:  21, italian: "piacere",                english: "nice to meet you",                  category: "greetings" },
  { id:  22, italian: "benvenuto",              english: "welcome",                           category: "greetings" },
  { id:  23, italian: "salute!",                english: "cheers! / bless you!",              category: "greetings" },
  { id:  24, italian: "in bocca al lupo!",      english: "good luck! (lit. in the wolf's mouth)", category: "greetings" },
  { id:  25, italian: "d'accordo",              english: "agreed / OK",                       category: "greetings" },

  // ── At the Restaurant (35) ────────────────────────────────────────────────
  { id:  26, italian: "ristorante",             english: "restaurant",                        category: "restaurant" },
  { id:  27, italian: "tavolo",                 english: "table",                             category: "restaurant" },
  { id:  28, italian: "menù",                   english: "menu",                              category: "restaurant" },
  { id:  29, italian: "cameriere",              english: "waiter",                            category: "restaurant" },
  { id:  30, italian: "cameriera",              english: "waitress",                          category: "restaurant" },
  { id:  31, italian: "il conto, per favore",   english: "the bill, please",                  category: "restaurant" },
  { id:  32, italian: "prenotazione",           english: "reservation",                       category: "restaurant" },
  { id:  33, italian: "vorrei...",              english: "I would like...",                   category: "restaurant" },
  { id:  34, italian: "posso avere...?",        english: "can I have...?",                    category: "restaurant" },
  { id:  35, italian: "per me",                 english: "for me",                            category: "restaurant" },
  { id:  36, italian: "buon appetito!",         english: "enjoy your meal!",                  category: "restaurant" },
  { id:  37, italian: "antipasto",              english: "starter / appetizer",               category: "restaurant" },
  { id:  38, italian: "primo piatto",           english: "first course (pasta / risotto)",    category: "restaurant" },
  { id:  39, italian: "secondo piatto",         english: "main course",                       category: "restaurant" },
  { id:  40, italian: "contorno",               english: "side dish",                         category: "restaurant" },
  { id:  41, italian: "dolce",                  english: "dessert / sweet",                   category: "restaurant" },
  { id:  42, italian: "pane",                   english: "bread",                             category: "restaurant" },
  { id:  43, italian: "acqua naturale",         english: "still water",                       category: "restaurant" },
  { id:  44, italian: "acqua frizzante",        english: "sparkling water",                   category: "restaurant" },
  { id:  45, italian: "vino rosso",             english: "red wine",                          category: "restaurant" },
  { id:  46, italian: "vino bianco",            english: "white wine",                        category: "restaurant" },
  { id:  47, italian: "una caraffa",            english: "a carafe",                          category: "restaurant" },
  { id:  48, italian: "pasta",                  english: "pasta",                             category: "restaurant" },
  { id:  49, italian: "pizza",                  english: "pizza",                             category: "restaurant" },
  { id:  50, italian: "carne",                  english: "meat",                              category: "restaurant" },
  { id:  51, italian: "pesce",                  english: "fish",                              category: "restaurant" },
  { id:  52, italian: "verdure",                english: "vegetables",                        category: "restaurant" },
  { id:  53, italian: "insalata",               english: "salad",                             category: "restaurant" },
  { id:  54, italian: "delizioso",              english: "delicious",                         category: "restaurant" },
  { id:  55, italian: "ottimo",                 english: "excellent",                         category: "restaurant" },
  { id:  56, italian: "senza...",               english: "without...",                        category: "restaurant" },
  { id:  57, italian: "sono allergico a...",    english: "I'm allergic to...",                category: "restaurant" },
  { id:  58, italian: "è piccante?",            english: "is it spicy?",                      category: "restaurant" },
  { id:  59, italian: "al dente",               english: "al dente (firm pasta)",             category: "restaurant" },
  { id:  60, italian: "coperto",                english: "cover charge",                      category: "restaurant" },

  // ── Bar & Café (20) ───────────────────────────────────────────────────────
  { id:  61, italian: "bar",                    english: "café / bar (Italian bar = café)",   category: "bar" },
  { id:  62, italian: "un caffè",               english: "an espresso",                       category: "bar" },
  { id:  63, italian: "cappuccino",             english: "cappuccino",                        category: "bar" },
  { id:  64, italian: "caffè macchiato",        english: "espresso with a drop of milk",      category: "bar" },
  { id:  65, italian: "cornetto",               english: "croissant",                         category: "bar" },
  { id:  66, italian: "brioche",                english: "brioche",                           category: "bar" },
  { id:  67, italian: "panino",                 english: "sandwich / roll",                   category: "bar" },
  { id:  68, italian: "aperitivo",              english: "aperitif / pre-dinner drink",       category: "bar" },
  { id:  69, italian: "uno spritz",             english: "a Spritz",                          category: "bar" },
  { id:  70, italian: "prosecco",               english: "Prosecco",                          category: "bar" },
  { id:  71, italian: "una birra",              english: "a beer",                            category: "bar" },
  { id:  72, italian: "birra alla spina",       english: "draft beer",                        category: "bar" },
  { id:  73, italian: "un succo",               english: "a juice",                           category: "bar" },
  { id:  74, italian: "analcolico",             english: "non-alcoholic drink",               category: "bar" },
  { id:  75, italian: "ghiaccio",               english: "ice",                               category: "bar" },
  { id:  76, italian: "digestivo",              english: "digestif",                          category: "bar" },
  { id:  77, italian: "grappa",                 english: "grappa",                            category: "bar" },
  { id:  78, italian: "limoncello",             english: "limoncello",                        category: "bar" },
  { id:  79, italian: "barista",                english: "barman / barista",                  category: "bar" },
  { id:  80, italian: "al bancone",             english: "at the counter (cheaper in Italy!)", category: "bar" },

  // ── Shopping (20) ─────────────────────────────────────────────────────────
  { id:  81, italian: "negozio",                english: "shop / store",                      category: "shopping" },
  { id:  82, italian: "mercato",                english: "market",                            category: "shopping" },
  { id:  83, italian: "supermercato",           english: "supermarket",                       category: "shopping" },
  { id:  84, italian: "quanto costa?",          english: "how much does it cost?",            category: "shopping" },
  { id:  85, italian: "caro",                   english: "expensive",                         category: "shopping" },
  { id:  86, italian: "economico",              english: "cheap / affordable",                category: "shopping" },
  { id:  87, italian: "in saldo",               english: "on sale",                           category: "shopping" },
  { id:  88, italian: "taglia",                 english: "size (clothing)",                   category: "shopping" },
  { id:  89, italian: "piccolo",                english: "small",                             category: "shopping" },
  { id:  90, italian: "medio",                  english: "medium",                            category: "shopping" },
  { id:  91, italian: "grande",                 english: "large / big",                       category: "shopping" },
  { id:  92, italian: "carta di credito",       english: "credit card",                       category: "shopping" },
  { id:  93, italian: "contanti",               english: "cash",                              category: "shopping" },
  { id:  94, italian: "scontrino",              english: "receipt",                           category: "shopping" },
  { id:  95, italian: "borsa",                  english: "bag",                               category: "shopping" },
  { id:  96, italian: "aperto",                 english: "open",                              category: "shopping" },
  { id:  97, italian: "chiuso",                 english: "closed",                            category: "shopping" },
  { id:  98, italian: "orari di apertura",      english: "opening hours",                     category: "shopping" },
  { id:  99, italian: "posso provarlo?",        english: "can I try it on?",                  category: "shopping" },
  { id: 100, italian: "farmacia",               english: "pharmacy",                          category: "shopping" },

  // ── Getting Around (22) ───────────────────────────────────────────────────
  { id: 101, italian: "dove si trova...?",      english: "where is...?",                      category: "transport" },
  { id: 102, italian: "come arrivo a...?",      english: "how do I get to...?",               category: "transport" },
  { id: 103, italian: "a sinistra",             english: "to the left",                       category: "transport" },
  { id: 104, italian: "a destra",               english: "to the right",                      category: "transport" },
  { id: 105, italian: "dritto",                 english: "straight ahead",                    category: "transport" },
  { id: 106, italian: "vicino",                 english: "nearby / close",                    category: "transport" },
  { id: 107, italian: "lontano",                english: "far",                               category: "transport" },
  { id: 108, italian: "treno",                  english: "train",                             category: "transport" },
  { id: 109, italian: "autobus",                english: "bus",                               category: "transport" },
  { id: 110, italian: "metropolitana",          english: "metro / subway",                    category: "transport" },
  { id: 111, italian: "taxi",                   english: "taxi",                              category: "transport" },
  { id: 112, italian: "fermata",                english: "stop / station",                    category: "transport" },
  { id: 113, italian: "biglietto",              english: "ticket",                            category: "transport" },
  { id: 114, italian: "andata e ritorno",       english: "return ticket",                     category: "transport" },
  { id: 115, italian: "binario",                english: "platform / track",                  category: "transport" },
  { id: 116, italian: "stazione",               english: "station",                           category: "transport" },
  { id: 117, italian: "aeroporto",              english: "airport",                           category: "transport" },
  { id: 118, italian: "centro città",           english: "city centre",                       category: "transport" },
  { id: 119, italian: "mappa",                  english: "map",                               category: "transport" },
  { id: 120, italian: "parcheggio",             english: "parking",                           category: "transport" },
  { id: 121, italian: "traffico",               english: "traffic",                           category: "transport" },
  { id: 122, italian: "noleggiare",             english: "to hire / rent",                    category: "transport" },

  // ── Numbers & Time (28) ───────────────────────────────────────────────────
  { id: 123, italian: "uno",                    english: "one",                               category: "numbers" },
  { id: 124, italian: "due",                    english: "two",                               category: "numbers" },
  { id: 125, italian: "tre",                    english: "three",                             category: "numbers" },
  { id: 126, italian: "quattro",                english: "four",                              category: "numbers" },
  { id: 127, italian: "cinque",                 english: "five",                              category: "numbers" },
  { id: 128, italian: "sei",                    english: "six",                               category: "numbers" },
  { id: 129, italian: "sette",                  english: "seven",                             category: "numbers" },
  { id: 130, italian: "otto",                   english: "eight",                             category: "numbers" },
  { id: 131, italian: "nove",                   english: "nine",                              category: "numbers" },
  { id: 132, italian: "dieci",                  english: "ten",                               category: "numbers" },
  { id: 133, italian: "venti",                  english: "twenty",                            category: "numbers" },
  { id: 134, italian: "trenta",                 english: "thirty",                            category: "numbers" },
  { id: 135, italian: "cento",                  english: "one hundred",                       category: "numbers" },
  { id: 136, italian: "mille",                  english: "one thousand",                      category: "numbers" },
  { id: 137, italian: "che ora è?",             english: "what time is it?",                  category: "numbers" },
  { id: 138, italian: "sono le...",             english: "it is... o'clock",                  category: "numbers" },
  { id: 139, italian: "mattina",                english: "morning",                           category: "numbers" },
  { id: 140, italian: "pomeriggio",             english: "afternoon",                         category: "numbers" },
  { id: 141, italian: "sera",                   english: "evening",                           category: "numbers" },
  { id: 142, italian: "notte",                  english: "night",                             category: "numbers" },
  { id: 143, italian: "oggi",                   english: "today",                             category: "numbers" },
  { id: 144, italian: "ieri",                   english: "yesterday",                         category: "numbers" },
  { id: 145, italian: "domani",                 english: "tomorrow",                          category: "numbers" },
  { id: 146, italian: "settimana",              english: "week",                              category: "numbers" },
  { id: 147, italian: "mese",                   english: "month",                             category: "numbers" },
  { id: 148, italian: "anno",                   english: "year",                              category: "numbers" },
  { id: 149, italian: "presto",                 english: "early / soon",                      category: "numbers" },
  { id: 150, italian: "tardi",                  english: "late",                              category: "numbers" },

  // ── Family & People (18) ──────────────────────────────────────────────────
  { id: 151, italian: "famiglia",               english: "family",                            category: "family" },
  { id: 152, italian: "padre / papà",           english: "father / dad",                      category: "family" },
  { id: 153, italian: "madre / mamma",          english: "mother / mum",                      category: "family" },
  { id: 154, italian: "figlio",                 english: "son",                               category: "family" },
  { id: 155, italian: "figlia",                 english: "daughter",                          category: "family" },
  { id: 156, italian: "fratello",               english: "brother",                           category: "family" },
  { id: 157, italian: "sorella",                english: "sister",                            category: "family" },
  { id: 158, italian: "marito",                 english: "husband",                           category: "family" },
  { id: 159, italian: "moglie",                 english: "wife",                              category: "family" },
  { id: 160, italian: "nonno",                  english: "grandfather",                       category: "family" },
  { id: 161, italian: "nonna",                  english: "grandmother",                       category: "family" },
  { id: 162, italian: "zio",                    english: "uncle",                             category: "family" },
  { id: 163, italian: "zia",                    english: "aunt",                              category: "family" },
  { id: 164, italian: "amico / amica",          english: "friend (male / female)",            category: "family" },
  { id: 165, italian: "ragazzo",                english: "boyfriend / boy",                   category: "family" },
  { id: 166, italian: "ragazza",                english: "girlfriend / girl",                 category: "family" },
  { id: 167, italian: "bambino",                english: "child / little boy",                category: "family" },
  { id: 168, italian: "bambina",                english: "child / little girl",               category: "family" },

  // ── Accommodation (18) ────────────────────────────────────────────────────
  { id: 169, italian: "hotel / albergo",        english: "hotel",                             category: "hotel" },
  { id: 170, italian: "camera",                 english: "room",                              category: "hotel" },
  { id: 171, italian: "camera singola",         english: "single room",                       category: "hotel" },
  { id: 172, italian: "camera doppia",          english: "double room (twin beds)",           category: "hotel" },
  { id: 173, italian: "letto matrimoniale",     english: "double bed",                        category: "hotel" },
  { id: 174, italian: "colazione inclusa",      english: "breakfast included",                category: "hotel" },
  { id: 175, italian: "chiave",                 english: "key",                               category: "hotel" },
  { id: 176, italian: "piano terra",            english: "ground floor",                      category: "hotel" },
  { id: 177, italian: "ascensore",              english: "lift / elevator",                   category: "hotel" },
  { id: 178, italian: "bagno",                  english: "bathroom",                          category: "hotel" },
  { id: 179, italian: "doccia",                 english: "shower",                            category: "hotel" },
  { id: 180, italian: "asciugamano",            english: "towel",                             category: "hotel" },
  { id: 181, italian: "aria condizionata",      english: "air conditioning",                  category: "hotel" },
  { id: 182, italian: "riscaldamento",          english: "heating",                           category: "hotel" },
  { id: 183, italian: "wi-fi",                  english: "wifi",                              category: "hotel" },
  { id: 184, italian: "check-in",               english: "check-in",                          category: "hotel" },
  { id: 185, italian: "check-out",              english: "check-out",                         category: "hotel" },
  { id: 186, italian: "passaporto",             english: "passport",                          category: "hotel" },

  // ── Useful Verbs (25) ─────────────────────────────────────────────────────
  { id: 187, italian: "volere",                 english: "to want  (voglio = I want)",         category: "verbs" },
  { id: 188, italian: "potere",                 english: "can / be able to  (posso = I can)",  category: "verbs" },
  { id: 189, italian: "dovere",                 english: "must / have to  (devo = I must)",    category: "verbs" },
  { id: 190, italian: "andare",                 english: "to go  (vado = I go)",               category: "verbs" },
  { id: 191, italian: "venire",                 english: "to come  (vengo = I come)",          category: "verbs" },
  { id: 192, italian: "fare",                   english: "to do / make  (faccio = I do)",      category: "verbs" },
  { id: 193, italian: "dire",                   english: "to say / tell  (dico = I say)",      category: "verbs" },
  { id: 194, italian: "mangiare",               english: "to eat  (mangio = I eat)",           category: "verbs" },
  { id: 195, italian: "bere",                   english: "to drink  (bevo = I drink)",         category: "verbs" },
  { id: 196, italian: "pagare",                 english: "to pay  (pago = I pay)",             category: "verbs" },
  { id: 197, italian: "comprare",               english: "to buy  (compro = I buy)",           category: "verbs" },
  { id: 198, italian: "cercare",                english: "to look for  (cerco = I look for)",  category: "verbs" },
  { id: 199, italian: "trovare",                english: "to find  (trovo = I find)",          category: "verbs" },
  { id: 200, italian: "prenotare",              english: "to book / reserve",                  category: "verbs" },
  { id: 201, italian: "capire",                 english: "to understand  (capisco)",           category: "verbs" },
  { id: 202, italian: "parlare",                english: "to speak / talk",                    category: "verbs" },
  { id: 203, italian: "aspettare",              english: "to wait  (aspetto = I wait)",        category: "verbs" },
  { id: 204, italian: "aiutare",                english: "to help  (aiuto = I help)",          category: "verbs" },
  { id: 205, italian: "chiamare",               english: "to call  (chiamo = I call)",         category: "verbs" },
  { id: 206, italian: "arrivare",               english: "to arrive  (arrivo = I arrive)",     category: "verbs" },
  { id: 207, italian: "partire",                english: "to leave / depart",                  category: "verbs" },
  { id: 208, italian: "tornare",                english: "to return  (torno = I return)",      category: "verbs" },
  { id: 209, italian: "dormire",                english: "to sleep  (dormo = I sleep)",        category: "verbs" },
  { id: 210, italian: "lavorare",               english: "to work  (lavoro = I work)",         category: "verbs" },
  { id: 211, italian: "studiare",               english: "to study  (studio = I study)",       category: "verbs" },

  // ── Describing Things (18) ────────────────────────────────────────────────
  { id: 212, italian: "bello / bella",          english: "beautiful / nice",                   category: "adjectives" },
  { id: 213, italian: "brutto / brutta",        english: "ugly / unpleasant",                  category: "adjectives" },
  { id: 214, italian: "buono / buona",          english: "good / tasty",                       category: "adjectives" },
  { id: 215, italian: "cattivo / cattiva",      english: "bad",                                category: "adjectives" },
  { id: 216, italian: "caldo / calda",          english: "hot / warm",                         category: "adjectives" },
  { id: 217, italian: "freddo / fredda",        english: "cold",                               category: "adjectives" },
  { id: 218, italian: "nuovo / nuova",          english: "new",                                category: "adjectives" },
  { id: 219, italian: "vecchio / vecchia",      english: "old",                                category: "adjectives" },
  { id: 220, italian: "stanco / stanca",        english: "tired",                              category: "adjectives" },
  { id: 221, italian: "felice",                 english: "happy",                              category: "adjectives" },
  { id: 222, italian: "triste",                 english: "sad",                                category: "adjectives" },
  { id: 223, italian: "facile",                 english: "easy",                               category: "adjectives" },
  { id: 224, italian: "difficile",              english: "difficult",                          category: "adjectives" },
  { id: 225, italian: "interessante",           english: "interesting",                        category: "adjectives" },
  { id: 226, italian: "noioso / noiosa",        english: "boring",                             category: "adjectives" },
  { id: 227, italian: "veloce",                 english: "fast",                               category: "adjectives" },
  { id: 228, italian: "lento / lenta",          english: "slow",                               category: "adjectives" },
  { id: 229, italian: "costoso / costosa",      english: "expensive",                          category: "adjectives" },

  // ── Emergencies (12) ──────────────────────────────────────────────────────
  { id: 230, italian: "aiuto!",                 english: "help!",                              category: "emergencies" },
  { id: 231, italian: "emergenza",              english: "emergency",                          category: "emergencies" },
  { id: 232, italian: "medico",                 english: "doctor",                             category: "emergencies" },
  { id: 233, italian: "ospedale",               english: "hospital",                           category: "emergencies" },
  { id: 234, italian: "mi fa male",             english: "it hurts / I'm in pain",             category: "emergencies" },
  { id: 235, italian: "mi sento male",          english: "I feel unwell",                      category: "emergencies" },
  { id: 236, italian: "ambulanza",              english: "ambulance",                          category: "emergencies" },
  { id: 237, italian: "polizia",                english: "police",                             category: "emergencies" },
  { id: 238, italian: "vigili del fuoco",       english: "fire brigade",                       category: "emergencies" },
  { id: 239, italian: "ho perso il portafoglio", english: "I've lost my wallet",               category: "emergencies" },
  { id: 240, italian: "rubato",                 english: "stolen",                             category: "emergencies" },
  { id: 241, italian: "pronto soccorso",        english: "emergency room / A&E",               category: "emergencies" },

  // ── Weather & Nature (14) ─────────────────────────────────────────────────
  { id: 242, italian: "che tempo fa?",          english: "what's the weather like?",           category: "weather" },
  { id: 243, italian: "fa bello",               english: "it's nice weather",                  category: "weather" },
  { id: 244, italian: "fa brutto",              english: "it's bad weather",                   category: "weather" },
  { id: 245, italian: "fa caldo",               english: "it's hot",                           category: "weather" },
  { id: 246, italian: "fa freddo",              english: "it's cold",                          category: "weather" },
  { id: 247, italian: "piove",                  english: "it's raining",                       category: "weather" },
  { id: 248, italian: "nevica",                 english: "it's snowing",                       category: "weather" },
  { id: 249, italian: "c'è vento",              english: "it's windy",                         category: "weather" },
  { id: 250, italian: "sole",                   english: "sun / sunshine",                     category: "weather" },
  { id: 251, italian: "nuvola",                 english: "cloud",                              category: "weather" },
  { id: 252, italian: "temporale",              english: "storm / thunderstorm",               category: "weather" },
  { id: 253, italian: "mare",                   english: "sea",                                category: "weather" },
  { id: 254, italian: "montagna",               english: "mountain",                           category: "weather" },
  { id: 255, italian: "spiaggia",               english: "beach",                              category: "weather" },
];
